# Generated by Django 2.2.16 on 2022-05-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220511_1958'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_author_user_following',
        ),
    ]
